### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by Versichert** [Sefiraat/Netheopoiesis#19]
Hey, there's the error log 
https://pastebin.com/RMXzpF4r

problem: can't open, after clicking on it in sf guide it stays in my hand

**Comment by Sefiraat** [comment]
Can you paste your /sf versions and the your plugin list /plugins please and thanks.

**Comment by Versichert** [comment]
Sf versions: https://pastebin.com/1gVqTMLP
Plugins: https://pastebin.com/9S8BfdLK
and we don't have cscorelib

**Comment by Sefiraat** [comment]
Found the issue :) Working on it now!

**Comment by Versichert** [comment]
Thanks

**Comment by Sefiraat** [comment]
@Versichert I've sorted the issue, you'll need to watch out for Build 8 of Netheopoiesis and add that in, after which you should be all set 👍

**Comment by Versichert** [comment]
Okay, sorry for delayed answears and Thnaks again for hepling :)

**Comment by Sefiraat** [comment]
Thanks for reporting and sorry for the bug! <3
