### ISSUE TITLE
breaking blocks in claim area (not sure)

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/Netheopoiesis#23]
put a nether beacon on nether beside a claimed place
( I don't have a person to try it with right now but it did broke mine when I put it outside of my claim and it did broke blocks inside of my claim so I'm worried it works even if people try to do)

**Comment by J3fftw1** [comment]
Please make sure before reporting.

**Comment by RIPISDRAD** [comment]
if i could I'd try but cant right now till 2 days later that's why I told u guys

**Comment by J3fftw1** [comment]
its been 4 days. Have you tested it?
No pressure if you didnt tested im just curious if i have to actually look in to the issue
