### ISSUE TITLE
Console warnings.

### ISSUE THREAD

**Issue by Leksandrya** [Sefiraat/Netheopoiesis#50]
I am getting these warnings after installing this add-on.

06.05 03:41:29 [Server] INFO Enabling Netheopoiesis vDEV - 18 (git 9d12cc6f)
06.05 03:41:29 [Server] INFO ########################################
06.05 03:41:29 [Server] INFO Netheopoiesis by Sefiraat, J3fftw
06.05 03:41:29 [Server] INFO ########################################
06.05 03:41:29 [Server] WARN Plugin 'Netheopoiesis' is creating timing 'Commands' - this is deprecated behavior, please report it to the authors: Sefiraat, J3fftw
06.05 03:41:29 [Server] INFO [ACF] Enabled Asynchronous Tab Completion Support!
06.05 03:41:29 [Server] WARN Plugin 'Netheopoiesis' is creating timing 'Command: netheopoiesis' - this is deprecated behavior, please report it to the authors: Sefiraat, J3fftw
06.05 03:41:29 [Server] WARN Plugin 'Netheopoiesis' is creating timing 'Command: netheopoiesis mobcaps' - this is deprecated behavior, please report it to the authors: Sefiraat, J3fftw
06.05 03:41:29 [Server] WARN Plugin 'Netheopoiesis' is creating timing 'Command: netheopoiesis purgemobcap' - this is deprecated behavior, please report it to the authors: Sefiraat, J3fftw
06.05 03:41:29 [Server] WARN Plugin 'Netheopoiesis' is creating timing 'Command: netheopoiesis purgeallmobcap' - this is deprecated behavior, please report it to the authors: Sefiraat, J3fftw

**Comment by Sefiraat** [comment]
These are totally fine to receive and will automatically stop when Netheo is next updated :). Nothing to worry about but thanks for the report!
