### ISSUE TITLE
sweet seeds are bugged

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/Netheopoiesis#53]
I tried sweet seeds beside sand and no sugar cane grows on sand
sand= X
sweede seed = Y
I tried both these types and no sugar cane
XYX
and
-Y-
X-X
i even tried putting water beside it still no result
(jeff i accidentally push enter man u didnt have to closed it right away I was editing)
![2023-07-27_08 12 11](https://github.com/Sefiraat/Netheopoiesis/assets/76468672/1064dbb4-c2d2-4188-97ec-ad3b5af9dbcb)

**Comment by RIPISDRAD** [comment]
they wont grow on regular sand although they grow on nether sand beach biome

**Comment by RIPISDRAD** [comment]
https://cdn.discordapp.com/attachments/1135255190640017459/1135264532403593286/MnjUpAU.png

the way u put seed matter to be all in x or z
it changes every time server resets and is unpredictable
mmm
n n n
which m and n are seeds sometimes it work and sometimes
m n
m n
m n
will work

**Comment by Sefiraat** [comment]
This is correct. The sand must be a valid crus as well as sand leading to either desert or beach biome cruxes.

**Comment by RIPISDRAD** [comment]
then plz fix the lure cause u just typed sand not cruxes sand
