### ISSUE TITLE
itemstacker with combining tool

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/Netheopoiesis#57]
u dropping 3 netheo seed pastes on ground so u can click it with combining tool but it wont work with item stacker collecting them to 3x
and another bug is if u use (1x) m (1x) n (64x )t mnt is the pastes and u try to combine them it will combine but (63x) t gonna be destroyed as well

**Comment by Sefiraat** [comment]
We do not support itemstackers with this tool currently. I'll throw it on the list of support to add in the future. Thanks
